#import "RPCS3ConfigStore.h"
#import "RPCS3CoreBridge.h"

static NSString *RootPath(void) {
    RPCS3IOSCoreDiagnostics diagnostics = rpcs3_ios_core_diagnostics();
    return diagnostics.data_path ? ([NSString stringWithUTF8String:diagnostics.data_path] ?: @"") : @"";
}

static NSString *YAMLString(id value) {
    NSString *text = [[value description] stringByReplacingOccurrencesOfString:@"\\" withString:@"\\\\"];
    text = [text stringByReplacingOccurrencesOfString:@"\"" withString:@"\\\""];
    return [NSString stringWithFormat:@"\"%@\"", text];
}

NSString *RPCS3IOSConfigPath(void) {
    return [[RootPath() stringByAppendingPathComponent:@"config"] stringByAppendingPathComponent:@"config.yml"];
}

BOOL RPCS3IOSWriteConfig(NSDictionary *values, NSError **error) {
    NSString *path = RPCS3IOSConfigPath();
    if (!path.length) {
        if (error) *error = [NSError errorWithDomain:@"RPCS3IOS" code:1 userInfo:@{NSLocalizedDescriptionKey:@"RPCS3 data root is unavailable"}];
        return NO;
    }

    NSString *ppu = values[@"ppu_decoder"] ?: @"Interpreter";
    NSString *spu = values[@"spu_decoder"] ?: @"Interpreter";
    NSString *renderer = values[@"renderer"] ?: @"Metal";
    NSNumber *scale = values[@"resolution_scale"] ?: @100;
    NSNumber *vsync = values[@"vsync"] ?: @YES;
    NSString *audio = values[@"audio_backend"] ?: @"AudioUnit";
    NSNumber *buffering = values[@"audio_buffering"] ?: @YES;
    NSString *network = values[@"network_status"] ?: @"Disconnected";
    NSString *language = values[@"language"] ?: @"English";
    NSNumber *fps = values[@"preferred_fps"] ?: @60;
    NSString *pad = values[@"pad_handler"] ?: @"iOS Game Controller";

    NSMutableString *yaml = [NSMutableString string];
    [yaml appendString:@"# Generated by RPCS3 iOS. Values mirror the upstream config categories.\n"];
    [yaml appendFormat:@"Core:\n  PPU Decoder: %@\n  SPU Decoder: %@\n", YAMLString(ppu), YAMLString(spu)];
    [yaml appendFormat:@"Video:\n  Renderer: %@\n  Resolution Scale: %@\n  VSync: %@\n  Preferred Frame Rate: %@\n", YAMLString(renderer), scale, vsync.boolValue ? @"true" : @"false", fps];
    [yaml appendFormat:@"Audio:\n  Renderer: %@\n  Enable Buffering: %@\n", YAMLString(audio), buffering.boolValue ? @"true" : @"false"];
    [yaml appendFormat:@"Network:\n  Network Status: %@\n", YAMLString(network)];
    [yaml appendFormat:@"System:\n  Language: %@\n", YAMLString(language)];
    [yaml appendFormat:@"Input/Output:\n  Pad Handler: %@\n", YAMLString(pad)];
    [yaml appendFormat:@"UI:\n  Confirm Exit: %@\n  Show Trophy Popups: %@\n  Touch Overlay: %@\n  Motion Controls: %@\n",
     [values[@"confirm_exit"] boolValue] ? @"true" : @"false",
     [values[@"show_trophy_popups"] boolValue] ? @"true" : @"false",
     [values[@"touch_overlay"] boolValue] ? @"true" : @"false",
     [values[@"motion_controls"] boolValue] ? @"true" : @"false"];

    NSString *directory = path.stringByDeletingLastPathComponent;
    [NSFileManager.defaultManager createDirectoryAtPath:directory withIntermediateDirectories:YES attributes:nil error:error];
    if (error && *error) return NO;

    NSString *temporary = [path stringByAppendingString:@".tmp"];
    if (![yaml writeToFile:temporary atomically:YES encoding:NSUTF8StringEncoding error:error]) return NO;
    [NSFileManager.defaultManager removeItemAtPath:path error:nil];
    return [NSFileManager.defaultManager moveItemAtPath:temporary toPath:path error:error];
}

NSString *RPCS3IOSReadConfig(void) {
    NSString *text = [NSString stringWithContentsOfFile:RPCS3IOSConfigPath() encoding:NSUTF8StringEncoding error:nil];
    return text ?: @"No generated RPCS3 config exists yet.";
}

NSString *RPCS3IOSReadLatestLog(void) {
    NSString *logs = [RootPath() stringByAppendingPathComponent:@"logs"];
    NSArray<NSString *> *names = [NSFileManager.defaultManager contentsOfDirectoryAtPath:logs error:nil] ?: @[];
    NSArray<NSString *> *sorted = [names sortedArrayUsingComparator:^NSComparisonResult(NSString *a, NSString *b) {
        NSDictionary *aa = [NSFileManager.defaultManager attributesOfItemAtPath:[logs stringByAppendingPathComponent:a] error:nil];
        NSDictionary *bb = [NSFileManager.defaultManager attributesOfItemAtPath:[logs stringByAppendingPathComponent:b] error:nil];
        return [bb.fileModificationDate compare:aa.fileModificationDate];
    }];
    for (NSString *name in sorted) {
        NSString *path = [logs stringByAppendingPathComponent:name];
        NSString *text = [NSString stringWithContentsOfFile:path encoding:NSUTF8StringEncoding error:nil];
        if (text.length) return text;
    }
    return @"No RPCS3 log has been written yet.";
}
