set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_VERSION 26.0)
set(CMAKE_SYSTEM_PROCESSOR arm64 CACHE STRING "Target processor")
set(CMAKE_OSX_SYSROOT iphoneos CACHE STRING "iPhoneOS SDK")
set(CMAKE_OSX_DEPLOYMENT_TARGET 26.0 CACHE STRING "Minimum iOS version")
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "Target architecture")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_STANDARD 17)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_OBJCXX_STANDARD 20)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED NO)
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED NO)
set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH YES)
set(CMAKE_XCODE_ATTRIBUTE_SUPPORTED_PLATFORMS iphoneos)
set(CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "1,2")

add_compile_definitions(
  RPCS3_IOS=1
  RPCS3_PLATFORM_MOBILE=1
  RPCS3_PLATFORM_DESKTOP=0
)
